[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-gradle" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
benchmark = { id = "org.jetbrains.kotlinx.benchmark", version.ref = "benchmark" }
allopen = { id = "org.jetbrains.kotlin.plugin.allopen", version.ref = "allopen" }

[versions]
java = "21"
kotlin = "2.2.21"
ktlint-gradle = "14.0.1"
junit = "6.0.1"
junit-pioneer = "2.3.0"
assertj = "3.27.6"
kotest = "6.0.5"
spotless = "8.1.0"
benchmark = "0.4.14"
allopen = "2.2.21"
lombok = "1.18.42"

[libraries]
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
junit-pioneer = { group = "org.junit-pioneer", name = "junit-pioneer", version.ref = "junit-pioneer" }
assertj-core = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }
kotest = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "kotest" }
benchmark = { group = "org.jetbrains.kotlinx", name = "kotlinx-benchmark-runtime", version.ref = "benchmark" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
